spring:
  application:
    name: flashdeal-commerce
  
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/flashdeal_primary
      username: flashdeal
      password: flashdeal123
      driver-class-name: org.postgresql.Driver
    
    secondary:
      url: jdbc:mysql://localhost:3306/flashdeal_secondary
      username: flashdeal
      password: flashdeal123
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.flashdeal: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom Application Properties
flashdeal:
  order:
    payment-timeout: 180000  # 3분 (밀리초)
    max-quantity-per-user: 5
  
  security:
    jwt:
      secret: flashdeal-secret-key-change-in-production
      expiration: 86400000  # 24시간
  
  redis:
    cache:
      default-ttl: 300  # 5분
      stock-ttl: 60     # 1분
