spring:
  datasource:
    url: jdbc:mysql://mysql:3306/flashdeal_commerce
    username: flashdeal
    password: flashdeal123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  data:
    redis:
      host: redis
      port: 6379
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.flashdeal: DEBUG
