spring:
  h2:
    console:
      enabled: true
  
  datasource:
    primary:
      url: jdbc:h2:mem:flashdeal_primary;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    
    secondary:
      url: jdbc:h2:mem:flashdeal_secondary;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
      driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    com.flashdeal: DEBUG
